name: sqflite_common_test
description: SQFlite test package
version: 0.4.0-nullsafety.0
publish_to: none

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dependencies:
  sqflite_common: '>=2.0.0-nullsafety.0'

dev_dependencies:
  process_run: '>=0.11.0+2'
  test: '>=1.16.0-nullsafety.10'
  pedantic: '>=1.10.0-nullsafety.0'
  sqflite_common_ffi:
    path: ../sqflite_common_ffi

dependency_overrides:
  sqflite_common:
    path: ../sqflite_common
