name: sqflite_common
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common
description: Dart wrapper on SQLite, a self-contained, high-reliability, embedded, SQL database engine.
version: 2.0.0-nullsafety.1

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dependencies:
  synchronized: '>=3.0.0-nullsafety.0 <4.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  meta: '>=1.3.0-nullsafety.6 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.11.0+2'
  http:
  test: '>=1.16.0-nullsafety.10'
  test_api: '>=0.2.19-nullsafety.6'
  pub_semver:
