name: sqflite_example
description: Demonstrates how to use the sqflite plugin.

dependencies:
  func: any
  path: any
  collection: any
  flutter:
    sdk: flutter
  path_provider: '>=0.3.0'
  sqflite:
    path: ../


dev_dependencies:
  test: any
  dev_test: any
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/example.db

# dev only
# dependency_overrides:
#  synchronized:
#    path: ../../synchronized.dart