name: sqflite
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/sqflite
description: SQLite flutter plugin
version: 0.2.2

flutter:
  plugin:
    androidPackage: com.tekartik.sqflite
    pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  synchronized: any

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter