name: sqflite
description: SQLite flutter plugin

flutter:
  plugin:
    androidPackage: com.tekartik.sqflite
    pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  synchronized: any
