name: sqflite
description: SQLite flutter plugin
version: 0.0.3

flutter:
  plugin:
    androidPackage: com.tekartik.sqflite
    pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  synchronized: any

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter