name: sqflite
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 2.0.0-nullsafety.2

environment:
  sdk: '>=2.12.0-29 <3.0.0'
  flutter: ">=1.24.0-10 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tekartik.sqflite
        pluginClass: SqflitePlugin
      ios:
        pluginClass: SqflitePlugin
      macos:
        pluginClass: SqflitePlugin


dependencies:
  flutter:
    sdk: flutter
  sqflite_common: '>=2.0.0-nullsafety.2 <3.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0-nullsafety.3'
  process_run: '>=0.11.0+2'
  http: '>=0.12.2'
  flutter_test:
    sdk: flutter
  test_api:
  pub_semver:

# Temp for nnbd support
# dependency_overrides:
#  sqflite_common:
#    path: ../sqflite_common