name: sqflite_common_ffi_web_support
description: sqflite_common_ffi_web support tools and basic test app.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.7.0
  service_worker: '>=0.3.0-dev <2.0.0'
  sqflite_common_ffi_web:
    path: ../sqflite_common_ffi_web
dev_dependencies:
  build_runner: '>=2.1.4 <4.0.0'
  build_web_compilers: '>=3.2.1 <5.0.0'
  lints: '>=2.0.0 <4.0.0'

dependency_overrides:
  sqflite_common_ffi:
    path: ../../sqflite_common_ffi
  sqflite_common:
    path: ../../sqflite_common