name: sqflite_common_ffi_web_test
description: sqflite web test.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.7.0
  sqflite_common_ffi_web:
  sqflite_common_ffi:
  sqflite_common:
  sqflite_common_test:
    path: ../../sqflite_common_test
dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  process_run:

dependency_overrides:
  sqflite_common_ffi_web:
    path: ../sqflite_common_ffi_web
  sqflite_common_ffi:
    path: ../../sqflite_common_ffi
  sqflite_common:
    path: ../../sqflite_common
  sqflite_common_test:
    path: ../../sqflite_common_test